/**
 * Types for the RAG (Retrieval-Augmented Generation) subsystem.
 *
 * Pipeline: text → embedding (OpenAI text-embedding-3-small, 1536 dims)
 *         → vector store (Postgres + pgvector)
 *         → similarity search (cosine, top-K)
 *         → optional cheap Fugu reranker
 *         → injected into Layer 4 CONTEXT of the prompt composer
 *
 * Used by the agent runner to recover context that fell out of the
 * 30-message short-term window (long conversations, old facts, prior
 * memory summaries).
 */

export interface EmbeddingResult {
  /** 1536-dim float vector. */
  vector: number[];
  /** Model that produced the embedding. */
  model: string;
  /** Total tokens billed by the provider. */
  tokensUsed: number;
  /** Cost in USD for this single embed call. */
  costUsd: number;
}

export type VectorOwnerType = 'message' | 'fact' | 'memory_summary';

export interface VectorEntry {
  /** Unique row id (generated by caller — usually `${ownerType}:${ownerId}`). */
  id: string;
  /** What kind of source this vector represents. */
  ownerType: VectorOwnerType;
  /** Foreign key in the owning domain (Message.id, Fact.id, etc). */
  ownerId: string;
  /** Optional scope filters — set on insert so we can filter at search time. */
  conversationId?: string;
  agentId?: string;
  contactId?: string;
  /** Original text used to produce the embedding. Returned in search results. */
  content: string;
  /** Raw embedding (only populated when fetched explicitly — search omits it). */
  embedding: number[];
  /** Free-form metadata (timestamps, sender role, fact category, etc). */
  metadata: Record<string, any>;
  /** ISO timestamp of when the entry was indexed. */
  createdAt: string;
}

export interface SearchScope {
  agentId?: string;
  contactId?: string;
  conversationId?: string;
  /** `'any'` (or undefined) skips the filter — searches all owner types. */
  ownerType?: VectorOwnerType | 'any';
}

export interface SearchQuery {
  /** Natural-language query. We embed this and run cosine similarity. */
  query: string;
  scope: SearchScope;
  /** Top-K results to return. Default 5. */
  k?: number;
  /** Cosine similarity threshold — entries below this are discarded. Default 0.7. */
  minScore?: number;
}

export interface SearchResult {
  entry: VectorEntry;
  /** Cosine similarity, 0.0–1.0 (higher = more similar). */
  score: number;
}

export interface RagConfig {
  /** OpenAI embedding model. */
  embeddingModel: string;
  /** Default top-K. */
  k: number;
  /** Default minimum cosine similarity. */
  minScore: number;
  /** Whether to run the cheap Fugu reranker after vector search. */
  rerankEnabled: boolean;
  /** Model id for the reranker (Sakana format, e.g. `sakana/fugu`). */
  rerankerModel: string;
}

/** Job payload for the BullMQ `rag-indexer` queue. */
export type IndexerJobData =
  | {
      type: 'index_message';
      messageId: string;
      content: string;
      scope: SearchScope;
      metadata?: Record<string, any>;
    }
  | {
      type: 'index_fact';
      factId: string;
      content: string;
      scope: SearchScope;
      metadata?: Record<string, any>;
    }
  | {
      type: 'index_memory_summary';
      summaryId: string;
      content: string;
      scope: SearchScope;
      metadata?: Record<string, any>;
    }
  | {
      type: 'delete_entry';
      id: string;
    };

export const DEFAULT_RAG_CONFIG: RagConfig = {
  embeddingModel: 'text-embedding-3-small',
  k: 5,
  minScore: 0.7,
  rerankEnabled: false,
  rerankerModel: 'openai/gpt-4o-mini',
};
